# Generated by Django 4.2.23 on 2025-06-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='incode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['incode'], name='shop_produc_incode_eabbcb_idx'),
        ),
    ]
