# Generated by Django 4.2.23 on 2025-07-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cena',
            field=models.FloatField(default=0.0),
        ),
    ]
