# Generated by Django 4.2.23 on 2025-07-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cena',
            field=models.CharField(default='0.0', max_length=15),
        ),
    ]
