# Generated by Django 4.2.27 on 2026-03-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articul',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cenoc',
            field=models.CharField(default='0.0', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='cenof',
            field=models.CharField(default='0.0', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='prop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='upak',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
