# Generated by Django 4.2.27 on 2026-03-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_articul_product_cenoc_product_cenof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='incode',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
